### **Орищенко Виталий**
#### Группа 1
#### @Vitosh992

In [87]:
import numpy as np

####Задание 1

In [88]:
a = np.matrix([[1, 2, 1],[-2, 1, 1]]) # Вносим матрицы из условия
b = np.matrix([[3, 1],[-1, 0],[2,4]])
c = np.matrix([[-2, 2],[1, -1],[1,2]])


In [89]:
try: # Так как размерность матрицы A и B различна, а складывать мы можем только матрицы отдной размерности, создадим структуру try/except,
  print(a+2*b) # которая будет реагировать на ошибку ValueError, и в этом случае матрица А будет транспонироваться
except ValueError:
  a = np.transpose(a)
  print(a+2*b)

[[7 0]
 [0 1]
 [5 9]]


In [90]:
print(b+2*c) # Со вторым выражением проблем нет, поэтому просто выводим результат

[[-1  5]
 [ 1 -2]
 [ 4  8]]


####Задание 2

In [91]:
z = np.zeros((8,8), dtype = int)
z[1::2, ::2] = 1  # Нечетные строки, четные столбцы
z[::2, 1::2] = 1  # Четные строки, нечетные столбцы
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


####Задание 3

In [92]:
v1 = np.arange(0, 1.5, 0.1) # наполняем два вектора до в рамках значений с шагом 0.1 и 1
v2 = np.arange(1,7,1)
v1 = v1.reshape((5,3)) # изменяем размерность массивов до необходимой
v2 = v2.reshape((3,2))
m1 = np.dot(v1,v2) # Проводим умножение полученных матриц
print(v1)


[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]


In [93]:
print(v2)

[[1 2]
 [3 4]
 [5 6]]


In [94]:
print(m1)

[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


####Задание 4

In [95]:
v3 = np.arange(1,72,2, dtype = "int32") # Создаем массив по исходному условию
print(v3)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]


In [96]:
result = v3[v3 % 3 == 0] # По условию кратности 3 отбираем необходимые элементы
print(result)

[ 3  9 15 21 27 33 39 45 51 57 63 69]
